version: '3.5'
services:
  payment:
    container_name: payment
    build: ./Payment
    ports:
      - "8282:80"
    depends_on:
      - register
      - registereditor
    networks:
      - proxynet
  register:
    container_name: register-main
    build: ./Register/RegisterMain
    ports:
      - "8280:80"
    networks:
      - proxynet
  registereditor:
    container_name: register-editor
    build: ./Register/RegisterEditor
    ports:
      - "8281:80"
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network
