-- MySQL Script generated by MySQL Workbench
-- Mon Oct 26 16:31:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema Polyclinic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Polyclinic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `polyclinic`;
CREATE SCHEMA `polyclinic` DEFAULT CHARACTER SET utf8;
USE `polyclinic`;

-- -----------------------------------------------------
-- Table `Polyclinic`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Polyclinic`.`tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(45) NOT NULL,
  `user_function` VARCHAR(45) NOT NULL,
  `day1` VARCHAR(45) NOT NULL,
  `day2` VARCHAR(45) NOT NULL,
  `users_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tokens_users_idx` (`users_email` ASC) VISIBLE,
  CONSTRAINT `fk_tokens_users`
    FOREIGN KEY (`users_email`)
    REFERENCES `Polyclinic`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Polyclinic`.`visits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_fio` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `speciality` VARCHAR(45) NOT NULL,
  `users_email` VARCHAR(45) NOT NULL,
  `doctor_fio` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visits_users1_idx` (`users_email` ASC) VISIBLE,
  CONSTRAINT `fk_visits_users1`
    FOREIGN KEY (`users_email`)
    REFERENCES `Polyclinic`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO users(email, password) VALUES('alex','1234');
INSERT INTO tokens(data,user_function,day1,day2,users_email) VALUES('abcd','GET','2020-1-1','2021-1-1','alex');
INSERT INTO tokens(data,user_function,day1,day2,users_email) VALUES('gfebr','CREATE','2020-1-1','2021-1-1','alex');
INSERT INTO tokens(data,user_function,day1,day2,users_email) VALUES('asdc','DELETE','2020-1-1','2021-1-1','alex');
INSERT INTO tokens(data,user_function,day1,day2,users_email) VALUES('okpo','UPDATE','2020-1-1','2021-1-1','alex');
INSERT INTO tokens(data,user_function,day1,day2,users_email) VALUES('okpo','ADD','2020-1-1','2021-1-1','alex');
INSERT INTO visits(user_fio,date,speciality,users_email,doctor_fio) VALUES('Alex Navilko','2001-1-2','THERAPEUT','alex','Ivan Ivanovich');

